Fatal error
Calling get_currentauth0userinfo() from a single page causes the following error message:
Fatal error: Cannot access self:: when no class scope is active in /nas/wp/www/staging/sumain/wp-content/plugins/auth0/WP_Auth0.php on line 695

There's no need to log error message when checking if current auth0 user is logged in.